version: "2"
services:
  node:
    image: "node:8.12-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: yarn run start

